################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/array.c \
../src/bitset.c \
../src/buffer.c \
../src/chunk.c \
../src/configfile-glue.c \
../src/configfile.c \
../src/configparser.c \
../src/connections-glue.c \
../src/connections.c \
../src/crc32.c \
../src/data_array.c \
../src/data_config.c \
../src/data_count.c \
../src/data_fastcgi.c \
../src/data_integer.c \
../src/data_string.c \
../src/etag.c \
../src/fdevent.c \
../src/fdevent_freebsd_kqueue.c \
../src/fdevent_linux_rtsig.c \
../src/fdevent_linux_sysepoll.c \
../src/fdevent_poll.c \
../src/fdevent_select.c \
../src/fdevent_solaris_devpoll.c \
../src/http-header-glue.c \
../src/http_auth.c \
../src/http_auth_digest.c \
../src/http_chunk.c \
../src/inet_ntop_cache.c \
../src/joblist.c \
../src/keyvalue.c \
../src/lemon.c \
../src/lempar.c \
../src/lighttpd-angel.c \
../src/log.c \
../src/md5.c \
../src/mod_access.c \
../src/mod_accesslog.c \
../src/mod_alias.c \
../src/mod_auth.c \
../src/mod_cgi.c \
../src/mod_cml.c \
../src/mod_cml_funcs.c \
../src/mod_cml_lua.c \
../src/mod_compress.c \
../src/mod_dirlisting.c \
../src/mod_evasive.c \
../src/mod_evhost.c \
../src/mod_expire.c \
../src/mod_extforward.c \
../src/mod_fastcgi.c \
../src/mod_flv_streaming.c \
../src/mod_indexfile.c \
../src/mod_magnet.c \
../src/mod_magnet_cache.c \
../src/mod_mysql_vhost.c \
../src/mod_proxy.c \
../src/mod_redirect.c \
../src/mod_rewrite.c \
../src/mod_rrdtool.c \
../src/mod_scgi.c \
../src/mod_secure_download.c \
../src/mod_setenv.c \
../src/mod_simple_vhost.c \
../src/mod_skeleton.c \
../src/mod_ssi.c \
../src/mod_ssi_expr.c \
../src/mod_ssi_exprparser.c \
../src/mod_staticfile.c \
../src/mod_status.c \
../src/mod_trigger_b4_dl.c \
../src/mod_userdir.c \
../src/mod_usertrack.c \
../src/mod_webdav.c \
../src/network.c \
../src/network_freebsd_sendfile.c \
../src/network_linux_sendfile.c \
../src/network_openssl.c \
../src/network_solaris_sendfilev.c \
../src/network_write.c \
../src/network_writev.c \
../src/plugin.c \
../src/proc_open.c \
../src/request.c \
../src/response.c \
../src/server.c \
../src/spawn-fcgi.c \
../src/splaytree.c \
../src/stat_cache.c \
../src/status_counter.c \
../src/stream.c 

O_SRCS += \
../src/array.o \
../src/bitset.o \
../src/buffer.o \
../src/chunk.o \
../src/configfile-glue.o \
../src/configfile.o \
../src/configparser.o \
../src/connections-glue.o \
../src/connections.o \
../src/crc32.o \
../src/data_array.o \
../src/data_config.o \
../src/data_count.o \
../src/data_fastcgi.o \
../src/data_integer.o \
../src/data_string.o \
../src/etag.o \
../src/fdevent.o \
../src/fdevent_freebsd_kqueue.o \
../src/fdevent_linux_rtsig.o \
../src/fdevent_linux_sysepoll.o \
../src/fdevent_poll.o \
../src/fdevent_select.o \
../src/fdevent_solaris_devpoll.o \
../src/http-header-glue.o \
../src/http_chunk.o \
../src/inet_ntop_cache.o \
../src/joblist.o \
../src/keyvalue.o \
../src/lemon.o \
../src/lighttpd-angel.o \
../src/log.o \
../src/md5.o \
../src/network.o \
../src/network_freebsd_sendfile.o \
../src/network_linux_sendfile.o \
../src/network_openssl.o \
../src/network_solaris_sendfilev.o \
../src/network_write.o \
../src/network_writev.o \
../src/plugin.o \
../src/proc_open-buffer.o \
../src/proc_open-proc_open.o \
../src/proc_open.o \
../src/request.o \
../src/response.o \
../src/server.o \
../src/spawn-fcgi.o \
../src/splaytree.o \
../src/stat_cache.o \
../src/status_counter.o \
../src/stream.o 

OBJS += \
./src/array.o \
./src/bitset.o \
./src/buffer.o \
./src/chunk.o \
./src/configfile-glue.o \
./src/configfile.o \
./src/configparser.o \
./src/connections-glue.o \
./src/connections.o \
./src/crc32.o \
./src/data_array.o \
./src/data_config.o \
./src/data_count.o \
./src/data_fastcgi.o \
./src/data_integer.o \
./src/data_string.o \
./src/etag.o \
./src/fdevent.o \
./src/fdevent_freebsd_kqueue.o \
./src/fdevent_linux_rtsig.o \
./src/fdevent_linux_sysepoll.o \
./src/fdevent_poll.o \
./src/fdevent_select.o \
./src/fdevent_solaris_devpoll.o \
./src/http-header-glue.o \
./src/http_auth.o \
./src/http_auth_digest.o \
./src/http_chunk.o \
./src/inet_ntop_cache.o \
./src/joblist.o \
./src/keyvalue.o \
./src/lemon.o \
./src/lempar.o \
./src/lighttpd-angel.o \
./src/log.o \
./src/md5.o \
./src/mod_access.o \
./src/mod_accesslog.o \
./src/mod_alias.o \
./src/mod_auth.o \
./src/mod_cgi.o \
./src/mod_cml.o \
./src/mod_cml_funcs.o \
./src/mod_cml_lua.o \
./src/mod_compress.o \
./src/mod_dirlisting.o \
./src/mod_evasive.o \
./src/mod_evhost.o \
./src/mod_expire.o \
./src/mod_extforward.o \
./src/mod_fastcgi.o \
./src/mod_flv_streaming.o \
./src/mod_indexfile.o \
./src/mod_magnet.o \
./src/mod_magnet_cache.o \
./src/mod_mysql_vhost.o \
./src/mod_proxy.o \
./src/mod_redirect.o \
./src/mod_rewrite.o \
./src/mod_rrdtool.o \
./src/mod_scgi.o \
./src/mod_secure_download.o \
./src/mod_setenv.o \
./src/mod_simple_vhost.o \
./src/mod_skeleton.o \
./src/mod_ssi.o \
./src/mod_ssi_expr.o \
./src/mod_ssi_exprparser.o \
./src/mod_staticfile.o \
./src/mod_status.o \
./src/mod_trigger_b4_dl.o \
./src/mod_userdir.o \
./src/mod_usertrack.o \
./src/mod_webdav.o \
./src/network.o \
./src/network_freebsd_sendfile.o \
./src/network_linux_sendfile.o \
./src/network_openssl.o \
./src/network_solaris_sendfilev.o \
./src/network_write.o \
./src/network_writev.o \
./src/plugin.o \
./src/proc_open.o \
./src/request.o \
./src/response.o \
./src/server.o \
./src/spawn-fcgi.o \
./src/splaytree.o \
./src/stat_cache.o \
./src/status_counter.o \
./src/stream.o 

C_DEPS += \
./src/array.d \
./src/bitset.d \
./src/buffer.d \
./src/chunk.d \
./src/configfile-glue.d \
./src/configfile.d \
./src/configparser.d \
./src/connections-glue.d \
./src/connections.d \
./src/crc32.d \
./src/data_array.d \
./src/data_config.d \
./src/data_count.d \
./src/data_fastcgi.d \
./src/data_integer.d \
./src/data_string.d \
./src/etag.d \
./src/fdevent.d \
./src/fdevent_freebsd_kqueue.d \
./src/fdevent_linux_rtsig.d \
./src/fdevent_linux_sysepoll.d \
./src/fdevent_poll.d \
./src/fdevent_select.d \
./src/fdevent_solaris_devpoll.d \
./src/http-header-glue.d \
./src/http_auth.d \
./src/http_auth_digest.d \
./src/http_chunk.d \
./src/inet_ntop_cache.d \
./src/joblist.d \
./src/keyvalue.d \
./src/lemon.d \
./src/lempar.d \
./src/lighttpd-angel.d \
./src/log.d \
./src/md5.d \
./src/mod_access.d \
./src/mod_accesslog.d \
./src/mod_alias.d \
./src/mod_auth.d \
./src/mod_cgi.d \
./src/mod_cml.d \
./src/mod_cml_funcs.d \
./src/mod_cml_lua.d \
./src/mod_compress.d \
./src/mod_dirlisting.d \
./src/mod_evasive.d \
./src/mod_evhost.d \
./src/mod_expire.d \
./src/mod_extforward.d \
./src/mod_fastcgi.d \
./src/mod_flv_streaming.d \
./src/mod_indexfile.d \
./src/mod_magnet.d \
./src/mod_magnet_cache.d \
./src/mod_mysql_vhost.d \
./src/mod_proxy.d \
./src/mod_redirect.d \
./src/mod_rewrite.d \
./src/mod_rrdtool.d \
./src/mod_scgi.d \
./src/mod_secure_download.d \
./src/mod_setenv.d \
./src/mod_simple_vhost.d \
./src/mod_skeleton.d \
./src/mod_ssi.d \
./src/mod_ssi_expr.d \
./src/mod_ssi_exprparser.d \
./src/mod_staticfile.d \
./src/mod_status.d \
./src/mod_trigger_b4_dl.d \
./src/mod_userdir.d \
./src/mod_usertrack.d \
./src/mod_webdav.d \
./src/network.d \
./src/network_freebsd_sendfile.d \
./src/network_linux_sendfile.d \
./src/network_openssl.d \
./src/network_solaris_sendfilev.d \
./src/network_write.d \
./src/network_writev.d \
./src/plugin.d \
./src/proc_open.d \
./src/request.d \
./src/response.d \
./src/server.d \
./src/spawn-fcgi.d \
./src/splaytree.d \
./src/stat_cache.d \
./src/status_counter.d \
./src/stream.d 


# Each subdirectory must supply rules for building sources it contributes
src/%.o: ../src/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


